### ISSUE TITLE
Update to use new version of Circuit Breaker library

### ISSUE THREAD

**Issue by neurosaurus** [IBM/swift-enterprise-demo#119]
Any plans to update this demo repo to the latest version of the Circuit Breaker library?

https://github.com/IBM-Swift/CircuitBreaker

**Comment by christiancompton** [comment]
@neurosaurus We will upgrade this demo repo with the latest release shortly.

**Comment by KyeMaloy97** [comment]
@neurosaurus The update to Circuit Breaker 5 is finished 🎉
