### ISSUE TITLE
Memory usage goes down after a while.

### ISSUE THREAD

**Issue by rolivieri** [IBM/swift-enterprise-demo#77]
Ricardos-MacBook-Pro:CircuitBreaker olivieri$ cf app SwiftEnterpriseDemo
Showing health and status for app SwiftEnterpriseDemo in org swiftdo@us.ibm.com / space applications-production as swiftdo@us.ibm.com...
OK

requested state: started
instances: 3/3
usage: 256M x 3 instances
urls: swiftenterprisedemo-capacitive-amphitheatre.mybluemix.net
last uploaded: Mon Mar 13 22:50:25 UTC 2017
stack: cflinuxfs2
buildpack: swift_buildpack

     state     since                    cpu    memory           disk           details
#0   running   2017-03-13 08:18:00 PM   0.1%   230.4M of 256M   694.3M of 1G
#1   running   2017-03-13 08:22:10 PM   0.4%   238.5M of 256M   694.3M of 1G
#2   running   2017-03-13 08:59:07 PM   0.1%   9M of 256M       694.3M of 1G
Ricardos-MacBook-Pro:CircuitBreaker olivieri$ cf app SwiftEnterpriseDemo
Showing health and status for app SwiftEnterpriseDemo in org swiftdo@us.ibm.com / space applications-production as swiftdo@us.ibm.com...
OK

requested state: started
instances: 3/3
usage: 256M x 3 instances
urls: swiftenterprisedemo-capacitive-amphitheatre.mybluemix.net
last uploaded: Mon Mar 13 22:50:25 UTC 2017
stack: cflinuxfs2
buildpack: swift_buildpack

     state     since                    cpu    memory           disk           details
#0   running   2017-03-13 08:18:00 PM   0.1%   231.6M of 256M   694.3M of 1G
#1   running   2017-03-13 08:22:10 PM   1.6%   231.7M of 256M   694.3M of 1G
#2   running   2017-03-13 08:59:07 PM   0.5%   11.5M of 256M    694.3M of 1G
Ricardos-MacBook-Pro:CircuitBreaker olivieri$ cf app SwiftEnterpriseDemo
Showing health and status for app SwiftEnterpriseDemo in org swiftdo@us.ibm.com / space applications-production as swiftdo@us.ibm.com...
OK

requested state: started
instances: 3/3
usage: 256M x 3 instances
urls: swiftenterprisedemo-capacitive-amphitheatre.mybluemix.net
last uploaded: Mon Mar 13 22:50:25 UTC 2017
stack: cflinuxfs2
buildpack: swift_buildpack

     state     since                    cpu    memory          disk           details
#0   running   2017-03-13 09:34:30 PM   0.3%   10M of 256M     694.3M of 1G
#1   running   2017-03-13 09:38:03 PM   0.0%   1.1M of 256M    399.8M of 1G
#2   running   2017-03-13 08:59:07 PM   0.4%   20.2M of 256M   694.3M of 1G
Ricardos-MacBook-Pro:CircuitBreaker olivieri$ cf app SwiftEnterpriseDemo
Showing health and status for app SwiftEnterpriseDemo in org swiftdo@us.ibm.com / space applications-production as swiftdo@us.ibm.com...
OK

requested state: started
instances: 2/2
usage: 256M x 2 instances
urls: swiftenterprisedemo-capacitive-amphitheatre.mybluemix.net
last uploaded: Mon Mar 13 22:50:25 UTC 2017
stack: cflinuxfs2
buildpack: swift_buildpack

     state     since                    cpu    memory          disk           details
#0   running   2017-03-13 09:34:30 PM   0.4%   10.1M of 256M   694.3M of 1G
#1   running   2017-03-13 09:38:03 PM   2.0%   7.9M of 256M    694.3M of 1G
Ricardos-MacBook-Pro:CircuitBreaker olivieri$ cf app SwiftEnterpriseDemo
Showing health and status for app SwiftEnterpriseDemo in org swiftdo@us.ibm.com / space applications-production as swiftdo@us.ibm.com...
OK

requested state: started
instances: 2/2
usage: 256M x 2 instances
urls: swiftenterprisedemo-capacitive-amphitheatre.mybluemix.net
last uploaded: Mon Mar 13 22:50:25 UTC 2017
stack: cflinuxfs2
buildpack: swift_buildpack

     state     since                    cpu    memory          disk           details
#0   running   2017-03-13 09:34:30 PM   0.1%   10.5M of 256M   694.3M of 1G
#1   running   2017-03-13 09:38:03 PM   0.2%   8.1M of 256M    694.3M of 1G
Ricardos-MacBook-Pro:CircuitBreaker olivieri$ cf app SwiftEnterpriseDemo
Showing health and status for app SwiftEnterpriseDemo in org swiftdo@us.ibm.com / space applications-production as swiftdo@us.ibm.com...
OK

requested state: started
instances: 2/2
usage: 256M x 2 instances
urls: swiftenterprisedemo-capacitive-amphitheatre.mybluemix.net
last uploaded: Mon Mar 13 22:50:25 UTC 2017
stack: cflinuxfs2
buildpack: swift_buildpack

     state     since                    cpu    memory         disk           details
#0   running   2017-03-13 09:34:30 PM   0.4%   11M of 256M    694.3M of 1G
#1   running   2017-03-13 09:38:03 PM   0.5%   8.6M of 256M   694.3M of 1G
Ricardos-MacBook-Pro:CircuitBreaker olivieri$ cf app SwiftEnterpriseDemo
Showing health and status for app SwiftEnterpriseDemo in org swiftdo@us.ibm.com / space applications-production as swiftdo@us.ibm.com...
OK

requested state: started
instances: 1/1
usage: 256M x 1 instances
urls: swiftenterprisedemo-capacitive-amphitheatre.mybluemix.net
last uploaded: Mon Mar 13 22:50:25 UTC 2017
stack: cflinuxfs2
buildpack: swift_buildpack

     state     since                    cpu    memory        disk           details
#0   running   2017-03-13 09:34:30 PM   0.7%   12M of

**Comment by christiancompton** [comment]
Pointer to this ticket in internal tracking: https://github.ibm.com/arf/planning-swift-solutions/issues/93
